version: "3.9"

services:
  speech-model-hub:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: PRODUCTION
    # ports:
    #   - "8080:8080"
    # restart: always

    deploy:
      mode: replicated
      replicas: 1

    network_mode: "host"
